### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by teunbrand**
Hi there,

Apologies for the cold PR without posting an issue first.
The ggplot2 package has changed its implementation of the guide system. This broke a few expectations of the tests. This PR adapts the tests so that they're both compatible with the current and development version of ggplot2.

Best wishes,
Teun

### CODE REVIEW

**Comment by ashenoy-cmbi** [comment]
Thanks, will take a look. Several other things broke with the new ggplot2 and I've been wondering if I should add grafify only works with the latest version.

**Comment by teunbrand** [comment]
IIRC there is nothing else *broken* in the sense that grafify doesn't work, but some warnings are emitted due to the switch to the `linewidth` aesthetic. Requiring the latest version is a decision that you can judge better than me.

**Review by ashenoy-cmbi — APPROVED** [review]

**Comment by teunbrand** [comment]
I may have been too eager to test for the 3.4.2 version while 3.4.3 has just been released. Apologies for this! Would you like me to put in an updated PR?

**Comment by ashenoy-cmbi** [comment]
Thanks. I have updated tests. Should be ok now - could you confirm when you get a chance?  Thanks.

**Pull request merged**
